### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by steinmetz1992** [gandhi187/VerteilteSysteme#1]
Please add a frontend to exercise 7 or we can't accept your solution.

**Comment by steinmetz1992** [comment]
Sorry I didn't see it but it's there! Very nice! I'm looking forward to create a business like Microsoft or Apple with you!

**Comment by steinmetz1992** [comment]
Sorry I have to correct myself: I don't get your shitty code

**Comment by gandhi187** [comment]
Hello mr steinmetz,
you dont get my code because of your shitty code skills. i think you should leave the wong-hu university of china
